[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"


[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"



[env]
TERM = "xterm-256color"

