[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
<<<<<<< HEAD
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
=======
family = "Hack Nerd Font"
style = "Bold"


[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
>>>>>>> 087c049 (adding tmux conf)
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"
<<<<<<< HEAD
=======



[env]
TERM = "xterm-256color"

>>>>>>> 087c049 (adding tmux conf)
